export const todoTypes = {
  ADD_ITEM_TODO: "ADD_ITEM_TODO",
  REMOVE_ITEM_TODO: "REMOVE_ITEM_TODO",
  EDIT_ITEM_TODO: "EDIT_ITEM_TODO",
  COMPLETE_ITEM_TODO: "COMPLETE_ITEM_TODO",
  ARCHIVE_ITEM_TODO: "ARCHIVE_ITEM_TODO",
};
